name: food-delivery

services:
  redis:
    image: redis:alpine
    restart: always
    ports:
      - ${REDIS_PORT}:6379
    command: redis-server --loglevel warning
    volumes:
      - redis:/data

  mongo:
    image: mongo
    restart: always
    ports:
      - ${MONGO_PORT}:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    volumes:
      - mongo:/data/db

  postgres:
    image: postgres
    restart: always
    shm_size: 128mb
    ports:
      - ${DATABASE_PORT}:5432
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    volumes:
      - postgres:/var/lib/postgresql/data

volumes:
  redis:
  postgres:
  mongo:
